---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: erik-lernia-app
  annotations:
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"erik-lernia-app:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"erik-lernia-app\")].image"}]'
spec:
  replicas: 2
  selector:
    matchLabels:
      app: erik-lernia-app
  template:
    metadata:
      labels:
        app: erik-lernia-app
    spec:
      containers:
      - name: erik-lernia-app
        image: erik-lernia-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

